CREATE DATABASE IF NOT EXISTS literales_cuore;
USE literales_cuore;

CREATE TABLE IF NOT EXISTS literales (
    id INT AUTO_INCREMENT,
    id_html VARCHAR(50) NOT NULL,
    id_element VARCHAR(50) NOT NULL,
    idioma ENUM('es', 'en', 'fr', 'de') NOT NULL,
    texto VARCHAR(255) NOT NULL,
    CONSTRAINT PK_literales PRIMARY KEY (id),
    CONSTRAINT UC_literales UNIQUE (id_html, id_element, idioma)
);

INSERT INTO literales (id_html, id_element, idioma, texto)
VALUES 
('index', 'iniciar_sesion', 'es', 'Inicia sesión'),
('index', 'registrarse', 'es', 'Regístrate'),
('index', 'fondo3', 'es', 'ERES LO QUE COMPARTES'),
('index', 'label_usuario', 'es', 'Usuario:'),
('index', 'usuario_title', 'es', 'El nick debe contener entre 2 y 50 carácteres: minúsculas, números, -, _.'),
('index', 'label_contrasena', 'es', 'Contraseña:'),
('index', 'clave_title', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('index', 'entrar', 'es', 'Iniciar sesión'),
('index', 'label_nick', 'es', 'Usuario:'),
('index', 'nick_title', 'es', 'El nick debe contener entre 2 y 50 carácteres: minúsculas, números, -, _.'),
('index', 'label_email', 'es', 'Correo:'),
('index', 'email_title', 'es', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('index', 'label_fecha_nacimiento', 'es', 'Fecha de nacimiento:'),
('index', 'label_sexo', 'es', 'Sexo:'),
('index', 'sexo_hombre', 'es', 'Hombre'),
('index', 'sexo_mujer', 'es', 'Mujer'),
('index', 'sexo_otros', 'es', 'Otro'),
('index', 'sexo_intersexo_hombre', 'es', 'Intersexo Hombre'),
('index', 'sexo_intersexo_mujer', 'es', 'Intersexo Mujer'),
('index', 'label_busqueda', 'es', 'Perfil búsqueda:'),
('index', 'busqueda_hombre', 'es', 'Hombres'),
('index', 'busqueda_mujer', 'es', 'Mujeres'),
('index', 'busqueda_intersexo_hombre', 'es', 'Intersexo - Hombre'),
('index', 'busqueda_intersexo_mujer', 'es', 'Intersexo - Mujer'),
('index', 'busqueda_hombre_mujer', 'es', 'Hombre - Mujer'),
('index', 'busqueda_hombre_intersexo_hombre', 'es', 'Hombre - Intersexo Hombre'),
('index', 'busqueda_hombre_intersexo_mujer', 'es', 'Hombre - Intersexo Mujer'),
('index', 'busqueda_mujer_intersexo_hombre', 'es', 'Mujer - Intersexo Hombre'),
('index', 'busqueda_mujer_intersexo_mujer', 'es', 'Mujer - Intersexo Mujer'),
('index', 'busqueda_intersexo_hombre_intersexo_mujer', 'es', 'Intersexo Hombre - Intersexo Mujer'),
('index', 'busqueda_todos', 'es', 'Todos'),
('index', 'label_imagen', 'es', 'Imagen:'),
('index', 'imagen_title', 'es', 'Sólo se permiten imágenes con extensión: .jpg, .jpeg, .png'),
('index', 'label_video', 'es', 'Video Presentacion:'),
('index', 'video_title', 'es', 'Sólo se permiten videos con extensión: .mp4, .webm, .ogv'),
('index', 'label_clave', 'es', 'Establecer contraseña:'),
('index', 'clave_registro_title', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('index', 'label_repetir_clave', 'es', 'Repetir contraseña:'),
('index', 'clave_confirma_title', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('index', 'noCoinciden', 'es', '!Las Contraseñas no coinciden, vuelve a intentarlo!'),
('index', 'coinciden', 'es', '!Las Contraseñas coinciden!'),
('index', 'label_check1_1', 'es', 'Certifico ser mayor de edad y aceptar las <a href="back/uploads/files/Español/condicionesDeUso.pdf" download>Condiciones Generales</a>. Descubre como tratamos tus datos en nuestra '),
('index', 'label_check1_2', 'es', '<a href="back/uploads/files/Español/privacidadYprotecciónDeDatos.pdf" download>Política de privacidad</a>, <a href="back/uploads/files/Español/políticaUsoDeCookies.pdf" download>Política de uso de cookies</a> y '),
('index', 'label_check1_3', 'es', '<a href="back/uploads/files/Español/dondeSeVePerfil.pdf" download>normas relativas a la visibilidad de los perfiles</a>.'),
('index', 'label_check2_1', 'es', 'Doy mi consentimiento para el procesamiento de mis <a href="back/uploads/files/Español/datosSensibles.pdf" download>datos confidenciales</a> y para el uso de '),
('index', 'label_check2_2', 'es', '<a href="back/uploads/files/Español/mensajesQueEnvioRecibo.pdf" download>filtros de mensajes seguros</a> por Cuore para brindarme el servicio.'),
('index', 'label_check3', 'es', 'Deseo recibir por correo electrónico ofertas comerciales relativas a los productos y servicios ofrecidos por los socios de Cuore S.L. Ver nuestros <a href="back/uploads/files/Español/colaboraciones.pdf" download>socios</a>.'),
('index', 'registrar', 'es', 'Registrarse'),
('index', 'server_error_1', 'es', 'El nick debe contener entre 2 y 50 carácteres: minúsculas, números, -, _.'),
('index', 'server_error_2', 'es', '¡Debe ser una fecha válida!'),
('index', 'server_error_3', 'es', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('index', 'server_error_4', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('index', 'server_error_5', 'es', 'Sólo se permiten imágenes con extensión: .jpg, .jpeg, .png '),
('index', 'server_error_6', 'es', 'El tamaño máximo de la imagen son 3000000 bytes.'),
('index', 'server_error_7', 'es', 'Sólo se permiten videos con extensión: .mp4, .webm, .ogv '),
('index', 'server_error_8', 'es', 'El tamaño máximo del video son 5000000 bytes.'),
('index', 'server_error_9', 'es', '¡Debes ser mayor de 18 años! ¡Estaremos encantados de verte pronto!'),
('index', 'server_error_501', 'es', '¡El usuario ya existe!'),
('index', 'server_error_502', 'es', '¡El email ya existe!'),
('index', 'server_error_503', 'es', '¡El usuario no existe!'),
('index', 'server_error_504', 'es', '¡La contraseña es incorrecta!'),
('index', 'server_error_505', 'es', '¡Error actualizando visitas!'),
('index', 'server_error_506', 'es', '¡Error insertando visitas!'),
('index', 'server_error_507', 'es', '¡Error publicando la imagen!'),
('index', 'server_error_508', 'es', '¡Error publicando el video!'),
('index', 'server_error_509', 'es', '¡Formato no permitido!'),
('index', 'error_ubicacion', 'es', 'Es necesario el permiso a la ubicación para continuar.'),
('index', 'registrado_correctamente', 'es', '!Muchas gracias por registrarte!\nInicia sesión para continuar.'),
('index', 'correcto', 'es', 'Éxito'),
('index', 'iniciar_sesion', 'en', 'Log in'),
('index', 'registrarse', 'en', 'Sign up'),
('index', 'fondo3', 'en', 'YOU ARE WHAT YOU SHARE'),
('index', 'label_usuario', 'en', 'User:'),
('index', 'usuario_title', 'en', 'The nick must contain between 2 and 50 characters: lowercase, numbers, -, _.'),
('index', 'label_contrasena', 'en', 'Password:'),
('index', 'clave_title', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('index', 'entrar', 'en', 'Log in'),
('index', 'label_nick', 'en', 'User:'),
('index', 'nick_title', 'en', 'The nick must contain between 2 and 50 characters: lowercase, numbers, -, _.'),
('index', 'label_email', 'en', 'E-mail:'),
('index', 'email_title', 'en', 'The email must have a format similar to: xxxx@xxxx.xxx'),
('index', 'label_fecha_nacimiento', 'en', 'Birth date:'),
('index', 'label_sexo', 'en', 'Sex:'),
('index', 'sexo_hombre', 'en', 'Man'),
('index', 'sexo_mujer', 'en', 'Woman'),
('index', 'sexo_otros', 'en', 'Other'),
('index', 'sexo_intersexo_hombre', 'en','Male Intersex'),
('index', 'sexo_intersexo_mujer', 'en', 'Female Intersex'),
('index', 'label_busqueda', 'en', 'Search profile:'),
('index', 'busqueda_hombre', 'en', 'Men'),
('index', 'busqueda_mujer', 'en', 'Women'),
('index', 'busqueda_intersexo_hombre', 'en', 'Male Intersex'),
('index', 'busqueda_intersexo_mujer', 'en', 'Female Intersex'),
('index', 'busqueda_hombre_mujer', 'en', 'Man - Woman'),
('index', 'busqueda_hombre_intersexo_hombre', 'en', 'Man - Male Intersex'),
('index', 'busqueda_hombre_intersexo_mujer', 'en', 'Man - Female Intersex'),
('index', 'busqueda_mujer_intersexo_hombre', 'en', 'Woman - Male Intersex'),
('index', 'busqueda_mujer_intersexo_mujer', 'en', 'Woman - Female Intersex'),
('index', 'busqueda_intersexo_hombre_intersexo_mujer', 'en', 'Male Intersex - Female Intersex'),
('index', 'busqueda_todos', 'en', 'Everybody'),
('index', 'label_imagen', 'en', 'Image:'),
('index', 'imagen_title', 'en', 'Only images with extension: .jpg, .jpeg, .png are allowed.'),
('index', 'label_video', 'en', 'Video presentation:'),
('index', 'video_title', 'en', 'Only videos with extension: .mp4, .webm, .ogv are allowed.'),
('index', 'label_clave', 'en', 'Set password:'),
('index', 'clave_registro_title', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('index', 'label_repetir_clave', 'en', 'Repeat password:'),
('index', 'clave_confirma_title', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('index', 'noCoinciden', 'en', 'The Passwords do not match, please try again!'),
('index', 'coinciden', 'en', 'The Passwords match!'),
('index', 'label_check1_1', 'en', 'I certify that I am of legal age and I accept the <a href="back/uploads/files/Ingles/condicionesDeUso.pdf" download>General conditions</a>. Discover how we treat your data in our '),
('index', 'label_check1_2', 'en', '<a href="back/uploads/files/Ingles/privacidadYprotecciónDeDatos.pdf" download>Privacy Policy</a>, <a href="back/uploads/files/Ingles/políticaUsoDeCookies.pdf" download>Cookie use policy</a> and '),
('index', 'label_check1_3', 'en', '<a href="back/uploads/files/Ingles/dondeSeVePerfil.pdf" download>rules on the visibility of profiles</a>.'),
('index', 'label_check2_1', 'en', 'I consent to the processing of my <a href="back/uploads/files/Ingles/datosSensibles.pdf" download>confidential data</a> and for the use of '),
('index', 'label_check2_2', 'en', '<a href="back/uploads/files/Ingles/mensajesQueEnvioRecibo.pdf" download>secure message filters</a> by Cuore to provide me with the service.'),
('index', 'label_check3', 'en', 'I wish to receive by e-mail commercial offers regarding the products and services offered by the partners of Cuore S.L. See our <a href="back/uploads/files/Ingles/colaboraciones.pdf" download>partners</a>.'),
('index', 'registrar', 'en', 'Check in'),
('index', 'server_error_1', 'en', 'The nick must contain between 2 and 50 characters: lowercase, numbers, -, _.'),
('index', 'server_error_2', 'en', 'Must be a valid date!'),
('index', 'server_error_3', 'en', 'The email must have a format similar to: xxxx@xxxx.xxx'),
('index', 'server_error_4', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('index', 'server_error_5', 'en', 'Only images with extension: .jpg, .jpeg, .png are allowed.'),
('index', 'server_error_6', 'en', 'The maximum image size is 3000000 bytes.'),
('index', 'server_error_7', 'en', 'Only videos with extension: .mp4, .webm, .ogv are allowed.'),
('index', 'server_error_8', 'en', 'The maximum video size is 5000000 bytes.'),
('index', 'server_error_9', 'en', "You should be over 18! We'll be happy to see you soon!"),
('index', 'server_error_501', 'en', 'The user already exists!'),
('index', 'server_error_502', 'en', 'The email already exists!'),
('index', 'server_error_503', 'en', 'The user does not exist!'),
('index', 'server_error_504', 'en', 'The password is incorrect!'),
('index', 'server_error_505', 'en', 'Error updating visits!'),
('index', 'server_error_506', 'en', 'Error inserting visits!'),
('index', 'server_error_507', 'en', "Error posting image"),
('index', 'server_error_508', 'en', 'Error posting the video'),
('index', 'server_error_509', 'en', 'Format not allowed!'),
('index', 'error_ubicacion', 'en', 'Permission to the location is required to proceed.'),
('index', 'registrado_correctamente', 'en', 'Thank you very much for registering!\nSign in to continue.'),
('index', 'correcto', 'en', 'Success'),
('index', 'iniciar_sesion', 'fr', 'Connexion'),
('index', 'registrarse', 'fr', "S'inscrire"),
('index', 'fondo3', 'fr', 'VOUS ÊTES CE QUE VOUS PARTAGEZ'),
('index', 'label_usuario', 'fr', 'Utilisateur:'),
('index', 'usuario_title', 'fr', 'Le pseudo doit contenir entre 2 et 50 caractères : minuscules, chiffres, -, _.'),
('index', 'label_contrasena', 'fr', 'Le mot de passe:'),
('index', 'clave_title', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('index', 'entrar', 'fr', 'Commencer la session'),
('index', 'label_nick', 'fr', 'Utilisateur:'),
('index', 'nick_title', 'fr', 'Le pseudo doit contenir entre 2 et 50 caractères : minuscules, chiffres, -, _.'),
('index', 'label_email', 'fr', 'E-mail:'),
('index', 'email_title', 'fr', "L'email doit avoir un format similaire à : xxxx@xxxx.xxx"),
('index', 'label_fecha_nacimiento', 'fr', 'Date de naissance:'),
('index', 'label_sexo', 'fr', 'Sexe:'),
('index', 'sexo_hombre', 'fr', 'Homme'),
('index', 'sexo_mujer', 'fr', 'Femme'),
('index', 'sexo_otros', 'fr', 'Autre'),
('index', 'sexo_intersexo_hombre', 'fr','Homme Intersexuée'),
('index', 'sexo_intersexo_mujer', 'fr', 'Femme Intersexuée'),
('index', 'label_busqueda', 'fr', 'Profil recherche:'),
('index', 'busqueda_hombre', 'fr', 'Les hommes'),
('index', 'busqueda_mujer', 'fr', 'Les femmes'),
('index', 'busqueda_intersexo_hombre', 'fr', 'Homme Intersexuée'),
('index', 'busqueda_intersexo_mujer', 'fr', 'Femme Intersexuée'),
('index', 'busqueda_hombre_mujer', 'fr', 'Homme - Femme'),
('index', 'busqueda_hombre_intersexo_hombre', 'fr', 'Homme - Homme Intersexuée'),
('index', 'busqueda_hombre_intersexo_mujer', 'fr', 'Homme - Femme Intersexuée'),
('index', 'busqueda_mujer_intersexo_hombre', 'fr', 'Femme - Homme Intersexuée'),
('index', 'busqueda_mujer_intersexo_mujer', 'fr', 'Femme _ Femme Intersex'),
('index', 'busqueda_intersexo_hombre_intersexo_mujer', 'fr', 'Homme Intersexuée - Femme Intersex'),
('index', 'busqueda_todos', 'fr', 'Tout le monde'),
('index', 'label_imagen', 'fr', 'Image:'),
('index', 'imagen_title', 'fr', 'Seules les images avec extension sont autorisées : . jpg, . jpeg, . png'),
('index', 'label_video', 'fr', 'Présentation vidéo:'),
('index', 'video_title', 'fr', 'Seules les vidéos avec extension sont autorisées : . mp4, . Webm, .ogv'),
('index', 'label_clave', 'fr', 'Définir le mot de passe:'),
('index', 'clave_registro_title', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('index', 'label_repetir_clave', 'fr', 'Répéter le mot de passe:'),
('index', 'clave_confirma_title', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('index', 'noCoinciden', 'fr', 'Les mots de passe ne correspondent pas, veuillez réessayer!'),
('index', 'coinciden', 'fr', 'Les mots de passe correspondent!'),
('index', 'label_check1_1', 'fr', 'Je certifie être majeur et accepter les <a href="back/uploads/files/Frances/condicionesDeUso.pdf" download>Conditions générales</a>. Découvrez comment nous traitons vos données dans notre '),
('index', 'label_check1_2', 'fr', '<a href="back/uploads/files/Frances/privacidadYprotecciónDeDatos.pdf" download>Politique de confidentialité</a>, <a href="back/uploads/files/Frances/políticaUsoDeCookies.pdf" download>Politique d utilisation des cookies</a> et '),
('index', 'label_check1_3', 'fr', '<a href="back/uploads/files/Frances/dondeSeVePerfil.pdf" download>règles relatives à la visibilité des profils</a>.'),
('index', 'label_check2_1', 'fr', 'Je consens au traitement de mes <a href="back/uploads/files/Frances/datosSensibles.pdf" download>données confidentielles</a> et pour l utilisation de '),
('index', 'label_check2_2', 'fr', '<a href="back/uploads/files/Frances/mensajesQueEnvioRecibo.pdf" download>filtres de messages sécurisés</a> par Cuore pour me fournir le service.'),
('index', 'label_check3', 'fr', 'Je souhaite recevoir par e-mail des offres commerciales concernant les produits et services proposés par les partenaires de Cuore S.L. <a href="back/uploads/files/Frances/colaboraciones.pdf" download>partenaires</a>.'),
('index', 'registrar', 'fr', 'Enregistrement'),
('index', 'server_error_1', 'fr', 'Le pseudo doit contenir entre 2 et 50 caractères : minuscules, chiffres, -, _.'),
('index', 'server_error_2', 'fr', 'Doit être une date valide!'),
('index', 'server_error_3', 'fr', "L'email doit avoir un format similaire à : xxxx@xxxx.xxx"),
('index', 'server_error_4', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('index', 'server_error_5', 'fr', 'Seules les images avec extension sont autorisées : . jpg, . jpeg, . png'),
('index', 'server_error_6', 'fr', "La taille maximale de l'image est de 3000000 octets."),
('index', 'server_error_7', 'fr', 'Seules les vidéos avec extension sont autorisées : . mp4, . Webm, .ogv'),
('index', 'server_error_8', 'fr', "La taille maximale de l'vidéo est de 5000000 octets."),
('index', 'server_error_9', 'fr', 'Vous devez avoir plus de 18 ans! Nous serons heureux de vous voir bientôt!'),
('index', 'server_error_501', 'fr', "L'utilisateur existe déjà!"),
('index', 'server_error_502', 'fr', "L'email existe déjà!"),
('index', 'server_error_503', 'fr', "Le nom d'utilisateur n'existe pas!"),
('index', 'server_error_504', 'fr', "Le mot de passe est incorrect!"),
('index', 'server_error_505', 'fr', "Erreur de mise à jour des visites!"),
('index', 'server_error_506', 'fr', "Erreur d'insertion de visites!"),
('index', 'server_error_507', 'fr', "Erreur de publication d'image!"),
('index', 'server_error_508', 'fr', 'Erreur lors de la publication de la vidéo!'),
('index', 'server_error_509', 'fr', 'Format non autorisé!'),
('index', 'error_ubicacion', 'fr', "L'autorisation de l'emplacement est nécessaire pour continuer."),
('index', 'registrado_correctamente', 'fr', 'Merci beaucoup pour votre inscription!\nConnectez-vous pour continuer.'),
('index', 'correcto', 'fr', 'Succès'),
('index', 'iniciar_sesion', 'de', 'Einloggen'),
('index', 'registrarse', 'de', 'Anmelden'),
('index', 'fondo3', 'de', 'DU BIST, WAS DU TEILST'),
('index', 'label_usuario', 'de', 'Benutzer:'),
('index', 'usuario_title', 'de', 'Der Nick muss zwischen 2 und 50 Zeichen enthalten: Kleinbuchstaben, Zahlen, -, _.'),
('index', 'label_contrasena', 'de', 'Passwort:'),
('index', 'clave_title', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('index', 'entrar', 'de', 'Einloggen'),
('index', 'label_nick', 'de', 'Benutzer:'),
('index', 'nick_title', 'de', 'Der Nick muss zwischen 2 und 50 Zeichen enthalten: Kleinbuchstaben, Zahlen, -, _.'),
('index', 'label_email', 'de', 'Email:'),
('index', 'email_title', 'de','Die E-Mail sollte ein ähnliches format haben wie: xxxx@xxxx.xxx'),
('index', 'label_fecha_nacimiento', 'de', 'Geburtsdatum:'),
('index', 'label_sexo', 'de', 'Sex:'),
('index', 'sexo_hombre', 'de', 'Mann'),
('index', 'sexo_mujer', 'de', 'Frau'),
('index', 'sexo_otros', 'de', 'Andere'),
('index', 'sexo_intersexo_hombre', 'de','Intersexueller Mann'),
('index', 'sexo_intersexo_mujer', 'de', 'Intersexuelle Frau'),
('index', 'label_busqueda', 'de', 'Suchprofil:'),
('index', 'busqueda_hombre', 'de', 'Frauen'),
('index', 'busqueda_mujer', 'de', 'Manner'),
('index', 'busqueda_intersexo_hombre', 'de', 'Intersexueller Mann'),
('index', 'busqueda_intersexo_mujer', 'de', 'Intersexuelle Frau'),
('index', 'busqueda_hombre_mujer', 'de', 'Mann - Frau'),
('index', 'busqueda_hombre_intersexo_hombre', 'de', 'Mann - Intersexueller Mann'),
('index', 'busqueda_hombre_intersexo_mujer', 'de', 'Mann - Intersexuelle Frau'),
('index', 'busqueda_mujer_intersexo_hombre', 'de', 'Frau - Intersexueller Mann'),
('index', 'busqueda_mujer_intersexo_mujer', 'de', 'Frau - Intersexueller Frau'),
('index', 'busqueda_intersexo_hombre_intersexo_mujer', 'de', 'Intersexueller Mann - Intersexueller Frau'),
('index', 'busqueda_todos', 'de', 'Jeder'),
('index', 'label_imagen', 'de', 'Bild:'),
('index', 'imagen_title', 'de', 'Nur Bilder mit der Erweiterung: jpg, . jpeg, . png sind erlaubt.'),
('index', 'label_video', 'de', 'Video Präsentation:'),
('index', 'video_title', 'de', 'Nur Videos mit der Erweiterung: .mp4, .webm, .ogv sind erlaubt.'),
('index', 'label_clave', 'de', 'Passwort festlegen:'),
('index', 'clave_registro_title', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('index', 'label_repetir_clave', 'de', 'Passwort wiederholen:'),
('index', 'clave_confirma_title', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('index', 'noCoinciden', 'de', 'Die Passwörter stimmen nicht überein, bitte versuchen Sie es erneut!'),
('index', 'coinciden', 'de', 'Die Passwörter stimmen überein!'),
('index', 'label_check1_1', 'de', 'Ich bestätige, dass ich volljährig bin und dass ich die <a href="back/uploads/files/Aleman/condicionesDeUso.pdf" download>Allgemeine Bedingungen</a>. Erfahren Sie, wie wir mit Ihren Daten umgehen '),
('index', 'label_check1_2', 'de', '<a href="back/uploads/files/Aleman/privacidadYprotecciónDeDatos.pdf" download>Datenschutzbestimmungen</a>, <a href="back/uploads/files/Aleman/políticaUsoDeCookies.pdf" download>Richtlinie zur Verwendung von Cookies</a> und '),
('index', 'label_check1_3', 'de', '<a href="back/uploads/files/Aleman/dondeSeVePerfil.pdf" download>Regeln für die Sichtbarkeit von Profilen</a>.'),
('index', 'label_check2_1', 'de', 'Ich stimme der Verarbeitung meiner <a href="back/uploads/files/Aleman/datosSensibles.pdf" download>vertrauliche Daten</a> und für die Verwendung von '),
('index', 'label_check2_2', 'de', '<a href="back/uploads/files/Aleman/mensajesQueEnvioRecibo.pdf" download>sichere Nachrichtenfilter</a> von Cuore, um mir den Service zu bieten.'),
('index', 'label_check3', 'de', 'Ich möchte per E-Mail kommerzielle Angebote zu den Produkten und Dienstleistungen der Partner von Cuore S.L. erhalten. <a href="back/uploads/files/Aleman/colaboraciones.pdf" download>partner</a>.'),
('index', 'registrar', 'de', 'Check-In'),
('index', 'server_error_1', 'de', 'Der Nick muss zwischen 2 und 50 Zeichen enthalten: Kleinbuchstaben, Zahlen, -, _.'),
('index', 'server_error_2', 'de', 'Muss ein gültiges Datum sein!'),
('index', 'server_error_3', 'de', 'Die E-Mail sollte ein ähnliches format haben wie: xxxx@xxxx.xxx'),
('index', 'server_error_4', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('index', 'server_error_5', 'de', 'Nur Bilder mit der Erweiterung: jpg, . jpeg, . png sind erlaubt.'),
('index', 'server_error_6', 'de', 'Die maximale Bildgröße beträgt 3000000 Bytes.'),
('index', 'server_error_7', 'de', 'Nur Videos mit der Erweiterung: .mp4, .webm, .ogv sind erlaubt.'),
('index', 'server_error_8', 'de', 'Die maximale Videogröße beträgt 5000000 Bytes.'),
('index', 'server_error_9', 'de', 'Sie müssen mindestens 18 Jahre alt sein! Wir freuen uns, Sie bald zu sehen!'),
('index', 'server_error_501', 'de', 'Der Benutzer existiert bereits!'),
('index', 'server_error_502', 'de', 'E-Mail existiert bereits!'),
('index', 'server_error_503', 'de', 'Der Benutzername existiert nicht!'),
('index', 'server_error_504', 'de', 'Das Passwort ist falsch!'),
('index', 'server_error_505', 'de', 'Fehler beim Aktualisieren der Besuche!'),
('index', 'server_error_506', 'de', 'Fehler beim Einfügen von Besuchen!'),
('index', 'server_error_507', 'de', 'Fehler beim posten des bildes!'),
('index', 'server_error_508', 'de', 'Fehler beim Posten des videos!'),
('index', 'server_error_509', 'de', 'Format nicht erlaubt!'),
('index', 'error_ubicacion', 'de', 'Um fortzufahren, ist eine genehmigung für den Standort erforderlich.'),
('index', 'registrado_correctamente', 'de', 'Vielen dank für die registrierung!\nMelden sie sich an, um fortzufahren.'),
('index', 'correcto', 'de', 'Erfolg'),
('perfil', 'restringido_no_superadmin', 'es', 'Zona restringida para usuarios no superadministradores'),
('perfil', 'titulo_nombre', 'es', 'Nombre: '),
('perfil', 'titulo_correo', 'es', 'Email: '),
('perfil', 'titulo_sexo', 'es', 'Sexo: '),
('perfil', 'texto_sexo_hombre', 'es', 'Hombre'),
('perfil', 'texto_sexo_mujer', 'es', 'Mujer'),
('perfil', 'texto_sexo_otros', 'es', 'Otro'),
('perfil', 'texto_sexo_intersexo_hombre', 'es', 'Intersexo Hombre'),
('perfil', 'texto_sexo_intersexo_mujer', 'es', 'Intersexo Mujer'),
('perfil', 'titulo_rol', 'es', 'Perfíl Búsqueda: '),
('perfil', 'texto_rol_hombre', 'es', 'Hombre'),
('perfil', 'texto_rol_mujer', 'es', 'Mujer'),
('perfil', 'texto_rol_intersexo_hombre', 'es', 'Intersexo Hombre'),
('perfil', 'texto_rol_intersexo_mujer', 'es', 'Intersexo Mujer'),
('perfil', 'texto_rol_hombre_mujer', 'es', 'Hombre - Mujer'),
('perfil', 'texto_rol_hombre_intersexo_hombre', 'es', 'Hombre - Intersexo Hombre'),
('perfil', 'texto_rol_hombre_intersexo_mujer', 'es', 'Hombre - Intersexo Mujer'),
('perfil', 'texto_rol_mujer_intersexo_hombre', 'es', 'Mujer - Intersexo Hombre'),
('perfil', 'texto_rol_mujer_intersexo_mujer', 'es', 'Mujer - Intersexo Mujer'),
('perfil', 'texto_rol_intersexo_hombre_intersexo_mujer', 'es', 'Intersexo Hombre - Intersexo Mujer'),
('perfil', 'texto_rol_todos', 'es', 'Todos'),
('perfil', 'h2_boton_imagenes', 'es', 'TUS IMÁGENES'),
('perfil', 'h2_boton_videos', 'es', 'TUS VÍDEOS'),
('perfil', 'boton_edicion', 'es', 'EDITAR<br>PERFIL'),
('perfil', 'boton_enviar_match', 'es', 'CITAS'),
('perfil', 'texto_match_envio', 'es', 'Se ha enviado correctamente. espere la respuesta'),
('perfil', 'boton_anadir_publi', 'es', 'AÑADIR<br>PUBLICACIÓN'),
('perfil', 'boton_guardar', 'es', 'GUARDAR<br>PERFIL'),
('perfil', 'publicacion_anadida_correctamente', 'es', '¡Publicación creada!'),
('perfil', 'titulo_borrar', 'es', '¿Está seguro?'),
('perfil', 'texto_borrar', 'es', 'No podrá deshacer esta acción.'),
('perfil', 'publicacion_borrada_correctamente', 'es', '¡Publicación eliminada!'),
('perfil', 'boton_cambiar_contra', 'es', 'CAMBIAR<br>CONTRASEÑA'),
('perfil', 'contrasena_actualizada_correctamente', 'es', '¡Contraseña actualizada!'),
('perfil', 'confirmar_alerta', 'es', 'Confirmar'),
('perfil', 'cancelar_alerta', 'es', 'Cancelar'),
('perfil', 'imgPerfil', 'es', 'Añadir Foto Perfíl'),
('perfil', 'texto_imagen', 'es', 'Comentario: '),
('perfil', 'boton_premium', 'es', 'HAZTE PREMIUM'),
('perfil', 'titulo_premium', 'es', "El hacerte PREMIUM será para siempre, solamente deberás abonar el módico precio de '19,99$'"),
('perfil', 'titulo_nombre_completo', 'es', 'Nombre completo: '),
('perfil', 'titulo_isbn', 'es', 'ISBN: '),
('perfil', 'titulo_caducidad', 'es', 'Caducidad: '),
('perfil', 'titulo_cvv', 'es', 'CVV: '),
('perfil', 'realizando_pago', 'es', 'Realizando pago, espere un segundo'),
('perfil', 'pago_realizado_correctamente', 'es', 'El pago se ha completado correctamente, ¡Gracias!'),
('perfil', 'correcto', 'es', 'Éxito'),
('perfil', 'p_menu1', 'es', 'CHAT PRIVADO'),
('perfil', 'p_menu2', 'es', 'SUGERENCIAS A CUORE'),
('perfil', 'p_menu3', 'es', 'CONTACTANOS'),
('perfil', 'p_menu4', 'es', 'CERRAR SESION'),
('perfil', 'titulo_clave_antigua', 'es', 'Clave actual: '),
('perfil', 'titulo_clave_nueva', 'es', 'Nueva contraseña: '),
('perfil', 'titulo_clave_nueva_conf', 'es', 'Confirmar nueva contraseña: '),
('perfil', 'video_publi', 'es', 'Tu navegador no soporta el video'),
('perfil', 'server_error_3', 'es', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('perfil', 'server_error_4', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('perfil', 'server_error_10', 'es', 'Máximo 255 caracteres'),
('perfil', 'server_error_11', 'es', 'Máximo 50 caracteres'),
('perfil', 'server_error_12', 'es', 'Sexo Incorrecto'),
('perfil', 'server_error_13', 'es', 'Perfil de busqueda incorrecto'),
('perfil', 'server_error_504', 'es', '¡La contraseña es incorrecta!'),
('perfil', 'server_error_509', 'es', '¡Formato no permitido!'),
('perfil', 'server_error_512', 'es', 'Error actualizando perfil'),
('perfil', 'server_error_513', 'es', 'El email pertenece a otro usuario'),
('perfil', 'server_error_514', 'es', 'Error actualizando imagen'),
('perfil', 'server_error_515', 'es', 'Error actualizando la contraseña'),
('perfil', 'server_error_516', 'es', 'Error subiendo publicación'),
('perfil', 'server_error_518', 'es', 'Error borrando publicación'),
('perfil', 'server_error_522', 'es', "Error al loguearse con este usuario"),
('perfil', 'server_error_523', 'es', "Error realizando el pago"),
('perfil', 'server_error_524', 'es', "El usuario no existe"),
('perfil', 'server_error_999', 'es', 'Token expirado'),
('perfil', 'validation_1', 'es', 'Añade clave actual'),
('perfil', 'validation_2', 'es', 'Añade nueva clave'),
('perfil', 'validation_3', 'es', 'Repetir clave'),
('perfil', 'validation_4', 'es', 'Ambas claves deben coincidir'),
('perfil', 'validation_5', 'es', 'La clave debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('perfil', 'validation_6', 'es', 'Debe añadir un archivo'),
('perfil', 'validation_7', 'es', 'Introduzca el nombre por favor'),
('perfil', 'validation_8', 'es', 'Introduzca el ISBN por favor'),
('perfil', 'validation_9', 'es', 'Introduzca una fehca válida por favor'),
('perfil', 'validation_10', 'es', 'Introduzca el cvv por favor'),
('perfil', 'validation_11', 'es', 'Tarjeta no válida, inténtelo de nuevo'),
('perfil', 'validation_12', 'es', 'La fecha introducida no es correcta'),
('perfil', 'validation_13', 'es', 'El cvv no es correcto'),
('perfil', 'restringido_no_superadmin', 'en', 'Restricted area for non-super administrator users'),
('perfil', 'titulo_nombre', 'en', 'Name: '),
('perfil', 'titulo_correo', 'en', 'Email: '),
('perfil', 'titulo_sexo', 'en', 'Sex: '),
('perfil', 'texto_sexo_hombre', 'en', 'Man'),
('perfil', 'texto_sexo_mujer', 'en', 'Woman'),
('perfil', 'texto_sexo_otros', 'en', 'Other'),
('perfil', 'texto_sexo_intersexo_hombre', 'en', 'Male Intersex'),
('perfil', 'texto_sexo_intersexo_mujer', 'en', 'Female Intersex'),
('perfil', 'titulo_rol', 'en', 'Search profile: '),
('perfil', 'texto_rol_hombre', 'en', 'Man'),
('perfil', 'texto_rol_mujer', 'en', 'Woman'),
('perfil', 'texto_rol_intersexo_hombre', 'en', 'Male Intersex'),
('perfil', 'texto_rol_intersexo_mujer', 'en', 'Female Intersex'),
('perfil', 'texto_rol_hombre_mujer', 'en', 'Man - Woman'),
('perfil', 'texto_rol_hombre_intersexo_hombre', 'en', 'Man - Male Intersex'),
('perfil', 'texto_rol_hombre_intersexo_mujer', 'en', 'Man - Female Intersex'),
('perfil', 'texto_rol_mujer_intersexo_hombre', 'en', 'Woman - Male Intersex'),
('perfil', 'texto_rol_mujer_intersexo_mujer', 'en', 'Woman - Female Intersex'),
('perfil', 'texto_rol_intersexo_hombre_intersexo_mujer', 'en', 'Male Intersex - Female Intersex'),
('perfil', 'texto_rol_todos', 'en', 'Everybody'),
('perfil', 'h2_boton_imagenes', 'en', 'YOUR IMAGES'),
('perfil', 'h2_boton_videos', 'en', 'YOUR VIDEOS'),
('perfil', 'boton_enviar_match', 'en', 'QUOTES'),
('perfil', 'texto_match_envio', 'en', 'It has been sent successfully, wait for the response'),
('perfil', 'boton_edicion', 'en', 'EDIT<br>PROFILE'),
('perfil', 'boton_anadir_publi', 'en', 'ADD<br>PUBLICATION'),
('perfil', 'boton_guardar', 'en', 'SAVE<br>PROFILE'),
('perfil', 'publicacion_anadida_correctamente', 'en', 'Publication created!'),
('perfil', 'titulo_borrar', 'en', 'Are you sure?'),
('perfil', 'texto_borrar', 'en', 'You will not be able to undo this action.'),
('perfil', 'publicacion_borrada_correctamente', 'en', 'Publication deleted!'),
('perfil', 'boton_cambiar_contra', 'en', 'CHANGE<br>PASSWORD'),
('perfil', 'contrasena_actualizada_correctamente', 'en', 'Updated password!'),
('perfil', 'confirmar_alerta', 'en', 'Confirm'),
('perfil', 'cancelar_alerta', 'en', 'Cancel'),
('perfil', 'imgPerfil', 'en', 'Add Photo Profile'),
('perfil', 'texto_imagen', 'en', 'Comment: '),
('perfil', 'boton_premium', 'en', 'GO PREMIUM'),
('perfil', 'titulo_premium', 'en', "Becoming PREMIUM will be forever, you only have to pay the small price of '$19.99'"),
('perfil', 'titulo_nombre_completo', 'en', 'Full name: '),
('perfil', 'titulo_isbn', 'en', 'ISBN: '),
('perfil', 'titulo_caducidad', 'en', 'Expiration: '),
('perfil', 'titulo_cvv', 'en', 'CVV: '),
('perfil', 'realizando_pago', 'en', 'Making payment, please wait a second'),
('perfil', 'pago_realizado_correctamente', 'en', 'Payment completed successfully, Thank you!'),
('perfil', 'correcto', 'en', 'Success'),
('perfil', 'p_menu1', 'en', 'PRIVATE CHAT'),
('perfil', 'p_menu2', 'en', 'SUGGESTIONS TO CUORE'),
('perfil', 'p_menu3', 'en', 'CONTACT US'),
('perfil', 'p_menu4', 'en', 'SIGN OFF'),
('perfil', 'titulo_clave_antigua', 'en', 'Current Password: '),
('perfil', 'titulo_clave_nueva', 'en', 'New Password: '),
('perfil', 'titulo_clave_nueva_conf', 'en', 'Confirm new password: '),
('perfil', 'video_publi', 'en', 'Your browser does not support the video'),
('perfil', 'server_error_3', 'en', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('perfil', 'server_error_4', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('perfil', 'server_error_10', 'en', 'Maximum 255 characters'),
('perfil', 'server_error_11', 'en', 'Maximum 50 characters'),
('perfil', 'server_error_12', 'en', 'Incorrect sex'),
('perfil', 'server_error_13', 'en', 'Incorrect search profile'),
('perfil', 'server_error_504', 'en', 'The password is incorrect!'),
('perfil', 'server_error_509', 'en', 'Format not allowed!'),
('perfil', 'server_error_512', 'en', 'Error updating profile'),
('perfil', 'server_error_513', 'en', 'The email belongs to another user'),
('perfil', 'server_error_514', 'en', 'Error updating image'),
('perfil', 'server_error_515', 'en', 'Error updating password'),
('perfil', 'server_error_516', 'en', 'Error uploading publication'),
('perfil', 'server_error_518', 'en', 'Error deleting publication'),
('perfil', 'server_error_522', 'en', "Error logging in with this user"),
('perfil', 'server_error_523', 'en', "Error making the payment"),
('perfil', 'server_error_524', 'en', "Username does not exist"),
('perfil', 'server_error_999', 'en', 'Expired token'),
('perfil', 'validation_1', 'en', 'Add current key'),
('perfil', 'validation_2', 'en', 'Add new key'),
('perfil', 'validation_3', 'en', 'Repeat key'),
('perfil', 'validation_4', 'en', 'Both keys must match'),
('perfil', 'validation_5', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('perfil', 'validation_6', 'en', 'You must add a file'),
('perfil', 'validation_7', 'en', 'Please enter name'),
('perfil', 'validation_8', 'en', 'Please enter ISBN'),
('perfil', 'validation_9', 'en', 'Please enter a valid date'),
('perfil', 'validation_10', 'en', 'Please enter cvv'),
('perfil', 'validation_11', 'en', 'Invalid card, please try again'),
('perfil', 'validation_12', 'en', 'The entered date is not correct'),
('perfil', 'validation_13', 'en', 'The cvv is not correct'),
('perfil', 'restringido_no_superadmin', 'fr', 'Zone restreinte pour les utilisateurs non super-administrateurs'),
('perfil', 'titulo_nombre', 'fr', 'Nom: '),
('perfil', 'titulo_correo', 'fr', 'Email: '),
('perfil', 'titulo_sexo', 'fr', 'Sexe: '),
('perfil', 'texto_sexo_hombre', 'fr', 'Homme'),
('perfil', 'texto_sexo_mujer', 'fr', 'Femme'),
('perfil', 'texto_sexo_otros', 'fr', 'Autre'),
('perfil', 'texto_sexo_intersexo_hombre', 'fr', 'Homme Intersexuée'),
('perfil', 'texto_sexo_intersexo_mujer', 'fr', 'Femme Intersexuée'),
('perfil', 'titulo_rol', 'fr', 'Profil recherche: '),
('perfil', 'texto_rol_hombre', 'fr', 'Homme'),
('perfil', 'texto_rol_mujer', 'fr', 'Femme'),
('perfil', 'texto_rol_intersexo_hombre', 'fr', 'Homme Intersexuée'),
('perfil', 'texto_rol_intersexo_mujer', 'fr', 'Femme Intersexuée'),
('perfil', 'texto_rol_hombre_mujer', 'fr', 'Homme - Femme'),
('perfil', 'texto_rol_hombre_intersexo_hombre', 'fr', 'Homme - Homme Intersexuée'),
('perfil', 'texto_rol_hombre_intersexo_mujer', 'fr', 'Homme - Femme Intersexuée'),
('perfil', 'texto_rol_mujer_intersexo_hombre', 'fr', 'Femme - Homme Intersexuée'),
('perfil', 'texto_rol_mujer_intersexo_mujer', 'fr', 'Femme - Femme Intersexuée'),
('perfil', 'texto_rol_intersexo_hombre_intersexo_mujer', 'fr', 'Homme Intersexuée - Femme Intersexuée'),
('perfil', 'texto_rol_todos', 'fr', 'Toutes'),
('perfil', 'h2_boton_imagenes', 'fr', 'VOS IMAGES'),
('perfil', 'h2_boton_videos', 'fr', 'VOS VIDÉOS'),
('perfil', 'boton_enviar_match', 'fr', 'DEVIS'),
('perfil', 'texto_match_envio', 'fr', 'Il a été envoyé avec succès, attendez la réponse'),
('perfil', 'boton_edicion', 'fr', "EDITER<br>PROFIL"),
('perfil', 'boton_anadir_publi', 'fr', 'AJOUTER<br>UNE PUBLICATION'),
('perfil', 'boton_guardar', 'fr', 'SAUVER<br>PROFIL'),
('perfil', 'publicacion_anadida_correctamente', 'fr', 'Publication créée!'),
('perfil', 'titulo_borrar', 'fr', 'Vous êtes sûr?'),
('perfil', 'texto_borrar', 'fr', 'Vous ne pourrez pas annuler cette action.'),
('perfil', 'publicacion_borrada_correctamente', 'fr', 'Publication supprimée!'),
('perfil', 'boton_cambiar_contra', 'fr', 'CHANGER LE<br>MOT DE PASSE'),
('perfil', 'contrasena_actualizada_correctamente', 'fr', 'Mot de passe actualisé!'),
('perfil', 'confirmar_alerta', 'fr', 'Confirmer'),
('perfil', 'cancelar_alerta', 'fr', 'Annuler'),
('perfil', 'imgPerfil', 'fr', 'Ajouter Photo Profilé'),
('perfil', 'texto_imagen', 'fr', 'Commentaire: '),
('perfil', 'boton_premium', 'fr', 'PASSER EN PREMIUM'),
('perfil', 'titulo_premium', 'fr', "Devenir PREMIUM sera pour toujours, vous n'aurez qu'à payer le petit prix de '$19.99'"),
('perfil', 'titulo_isbn', 'fr', 'ISBN: '),
('perfil', 'titulo_nombre_completo', 'fr', 'Nom complet: '),
('perfil', 'titulo_caducidad', 'fr', 'Expiration: '),
('perfil', 'titulo_cvv', 'fr', 'CVV: '),
('perfil', 'realizando_pago', 'fr', 'Paiement en cours, veuillez patienter une seconde'),
('perfil', 'pago_realizado_correctamente', 'fr', 'Le paiement a été effectué avec succès, Merci!'),
('perfil', 'correcto', 'fr', 'Succès'),
('perfil', 'p_menu1', 'fr', 'DISCUSSION PRIVÉE'),
('perfil', 'p_menu2', 'fr', 'SUGGESTIONS POUR CUORE'),
('perfil', 'p_menu3', 'fr', 'NOUS CONTACTER'),
('perfil', 'p_menu4', 'fr', 'FERMER SESSION'),
('perfil', 'titulo_clave_antigua', 'fr', 'Clé actuelle: '),
('perfil', 'titulo_clave_nueva', 'fr', 'nouveau mot de passe: '),
('perfil', 'titulo_clave_nueva_conf', 'fr', 'Confirmez le nouveau mot de passe: '),
('perfil', 'video_publi', 'fr', 'Votre navigateur ne supporte pas la vidéo'),
('perfil', 'server_error_3', 'fr', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('perfil', 'server_error_4', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('perfil', 'server_error_10', 'fr', '255 caractères maximum'),
('perfil', 'server_error_11', 'fr', '50 caractères maximum'),
('perfil', 'server_error_12', 'fr', 'Sexe Incorrect'),
('perfil', 'server_error_13', 'fr', 'Profil de recherche incorrect'),
('perfil', 'server_error_504', 'fr', 'Le mot de passe est incorrect!'),
('perfil', 'server_error_509', 'fr', 'Format non autorisé!'),
('perfil', 'server_error_512', 'fr', 'Erreur lors de la mise à jour du profil'),
('perfil', 'server_error_513', 'fr', "L'e-mail appartient à un autre utilisateur"),
('perfil', 'server_error_514', 'fr', "Erreur de mise à jour de l'image"),
('perfil', 'server_error_515', 'fr', 'Erreur de mise à jour du mot de passe'),
('perfil', 'server_error_516', 'fr', 'Erreur de téléchargement de la publication'),
('perfil', 'server_error_518', 'fr', "Erreur lors de la suppression d'une publication"),
('perfil', 'server_error_522', 'fr', "Erreur de connexion avec cet utilisateur"),
('perfil', 'server_error_523', 'fr', "Erreur lors du paiement"),
('perfil', 'server_error_524', 'fr', "Le nom d'utilisateur n'existe pas"),
('perfil', 'server_error_999', 'fr', 'Jeton expiré'),
('perfil', 'validation_1', 'fr', 'Ajouter la clé actuelle'),
('perfil', 'validation_2', 'fr', 'Ajouter une nouvelle clé'),
('perfil', 'validation_3', 'fr', 'Touche de répétition'),
('perfil', 'validation_4', 'fr', 'Les deux clés doivent correspondre'),
('perfil', 'validation_5', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('perfil', 'validation_6', 'fr', 'Vous devez ajouter un fichier'),
('perfil', 'validation_7', 'fr', 'Veuillez entrer le nom'),
('perfil', 'validation_8', 'fr', "Veuillez entrer l'ISBN"),
('perfil', 'validation_9', 'fr', 'Veuillez entrer une date valide'),
('perfil', 'validation_10', 'fr', 'Veuillez entrer CV'),
('perfil', 'validation_11', 'fr', 'Carte invalide, veuillez réessayer'),
('perfil', 'validation_12', 'fr', "La date saisie n'est pas correcte"),
('perfil', 'validation_13', 'fr', "Le cvv n'est pas correct"),
('perfil', 'restringido_no_superadmin', 'de', 'Eingeschränkter Bereich für Nicht-Superadministrator-Benutzer'),
('perfil', 'titulo_nombre', 'de', 'Name: '),
('perfil', 'titulo_correo', 'de', 'Email: '),
('perfil', 'titulo_sexo', 'de', 'Sex: '),
('perfil', 'texto_sexo_hombre', 'de', 'Mann'),
('perfil', 'texto_sexo_mujer', 'de', 'Frau'),
('perfil', 'texto_sexo_otros', 'de', 'Andere'),
('perfil', 'texto_sexo_intersexo_hombre', 'de', 'Intersexueller Mann'),
('perfil', 'texto_sexo_intersexo_mujer', 'de', 'Intersexuelle Frau'),
('perfil', 'titulo_rol', 'de', 'Suchprofil: '),
('perfil', 'texto_rol_hombre', 'de', 'Mann'),
('perfil', 'texto_rol_mujer', 'de', 'Frau'),
('perfil', 'texto_rol_intersexo_hombre', 'de', 'Intersexueller Mann'),
('perfil', 'texto_rol_intersexo_mujer', 'de', 'Intersexuelle Frau'),
('perfil', 'texto_rol_hombre_mujer', 'de', 'Mann - Frau'),
('perfil', 'texto_rol_hombre_intersexo_hombre', 'de', 'Mann - Intersexueller Mann'),
('perfil', 'texto_rol_hombre_intersexo_mujer', 'de', 'Mann - Intersexuelle Frau'),
('perfil', 'texto_rol_mujer_intersexo_hombre', 'de', 'Frau - Intersexueller Mann'),
('perfil', 'texto_rol_mujer_intersexo_mujer', 'de', 'Frau - Intersexuelle Frau'),
('perfil', 'texto_rol_intersexo_hombre_intersexo_mujer', 'de', 'Intersexueller Mann - Intersexuelle Frau'),
('perfil', 'texto_rol_todos', 'de', 'Alles'),
('perfil', 'h2_boton_imagenes', 'de', 'IHRE BILDER'),
('perfil', 'h2_boton_videos', 'de', 'IHRE VIDEOS'),
('perfil', 'boton_enviar_match', 'de', 'ZITATE'),
('perfil', 'texto_match_envio', 'de', 'Es wurde erfolgreich gesendet, warten sie auf die antwort'),
('perfil', 'boton_edicion', 'de', 'PROFIL<br>BEARBEITEN'),
('perfil', 'boton_anadir_publi', 'de', 'VERÖFFENTLICHUNG<br>HINZUFÜGEN'),
('perfil', 'boton_guardar', 'de', 'PROFIL<br>SPEICHERN'),
('perfil', 'publicacion_anadida_correctamente', 'de', 'Veröffentlichung erstellt!'),
('perfil', 'titulo_borrar', 'de', 'Sind Sie sicher?'),
('perfil', 'texto_borrar', 'de', 'Sie können diese Aktion nicht mehr rückgängig machen.'),
('perfil', 'publicacion_borrada_correctamente', 'de', 'Veröffentlichung gelöscht!'),
('perfil', 'boton_cambiar_contra', 'de', 'PASSWORT<br>ÄNDERN'),
('perfil', 'contrasena_actualizada_correctamente', 'de', 'Aktualisiertes Passwort!'),
('perfil', 'confirmar_alerta', 'de', 'Bestätigen'),
('perfil', 'cancelar_alerta', 'de', 'Stornieren'),
('perfil', 'imgPerfil', 'de', 'Foto hinzufügen Perfíl'),
('perfil', 'texto_imagen', 'de', 'Kommentar: '),
('perfil', 'boton_premium', 'de', 'PRÄMIE GEHEN'),
('perfil', 'titulo_premium', 'de', "PREMIUM zu werden wird für immer sein, Sie müssen nur den kleinen Preis von '$19.99' bezahlen."),
('perfil', 'titulo_nombre_completo', 'de', 'Vollständiger Name: '),
('perfil', 'titulo_isbn', 'de', 'ISBN: '),
('perfil', 'titulo_caducidad', 'de', 'Ablauf: '),
('perfil', 'titulo_cvv', 'de', 'CVV: '),
('perfil', 'realizando_pago', 'de', 'Zahlung ausführen, bitte warten Sie eine Sekunde'),
('perfil', 'pago_realizado_correctamente', 'de', 'Die Zahlung wurde erfolgreich abgeschlossen, danke!'),
('perfil', 'correcto', 'de', 'Erfolg'),
('perfil', 'p_menu1', 'de', 'PRIVATER CHAT'),
('perfil', 'p_menu2', 'de', 'VORSCHLÄGE ZU CUORE'),
('perfil', 'p_menu3', 'de', 'KONTAKTIERE UNS'),
('perfil', 'p_menu4', 'de', 'ABMELDEN'),
('perfil', 'titulo_clave_antigua', 'de', 'Aktueller Schlüssel: '),
('perfil', 'titulo_clave_nueva', 'de', 'Neues Kennwort: '),
('perfil', 'titulo_clave_nueva_conf', 'de', 'Bestätigen Sie das neue Passwort: '),
('perfil', 'video_publi', 'de', 'Ihr Browser unterstützt das Video nicht'),
('perfil', 'server_error_3', 'de', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('perfil', 'server_error_4', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('perfil', 'server_error_10', 'de', 'Maximal 255 Zeichen'),
('perfil', 'server_error_11', 'de', 'Maximal 50 Zeichen'),
('perfil', 'server_error_12', 'de', 'Falsches Geschlecht'),
('perfil', 'server_error_13', 'de', 'Falsches Suchprofil'),
('perfil', 'server_error_504', 'de', 'Das Passwort ist falsch!'),
('perfil', 'server_error_509', 'de', 'Format nicht erlaubt!'),
('perfil', 'server_error_512', 'de', 'Fehler beim Aktualisieren des Profils'),
('perfil', 'server_error_513', 'de', 'Die E-Mail gehört einem anderen Benutzer'),
('perfil', 'server_error_514', 'de', 'Fehler beim Aktualisieren des Bildes'),
('perfil', 'server_error_515', 'de', 'Fehler beim Aktualisieren des Passworts'),
('perfil', 'server_error_516', 'de', 'Fehler beim Hochladen der Veröffentlichung'),
('perfil', 'server_error_518', 'de', 'Fehler beim Löschen der Veröffentlichung'),
('perfil', 'server_error_522', 'de', "Fehler bei der Anmeldung mit diesem Benutzer"),
('perfil', 'server_error_523', 'de', "Fehler bei der Zahlung"),
('perfil', 'server_error_524', 'de', "Der benutzername existiert nicht"),
('perfil', 'server_error_999', 'de', 'Abgelaufenes Token'),
('perfil', 'validation_1', 'de', 'Aktuellen Schlüssel hinzufügen'),
('perfil', 'validation_2', 'de', 'Neuen Schlüssel hinzufügen'),
('perfil', 'validation_3', 'de', 'Taste wiederholen'),
('perfil', 'validation_4', 'de', 'Beide Schlüssel müssen übereinstimmen'),
('perfil', 'validation_5', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('perfil', 'validation_6', 'de', 'Sie müssen eine Datei hinzufügen'),
('perfil', 'validation_7', 'de', 'Bitte namen eingeben'),
('perfil', 'validation_8', 'de', 'Geben sie bitte die ISBN ein'),
('perfil', 'validation_9', 'de', 'Bitte gib ein korrektes Datum an'),
('perfil', 'validation_10', 'de', 'Geben Sie bitte den Lebenslauf ein'),
('perfil', 'validation_11', 'de', 'Ungültige Karte, bitte versuchen Sie es erneut'),
('perfil', 'validation_12', 'de', 'Das eingegebene Datum ist nicht korrekt'),
('perfil', 'validation_13', 'de', 'Der cvv ist nicht korrekt'),
('home', 'restringido_no_superadmin', 'es', 'Zona restringida para usuarios no superadministradores'),
('home', 'p_menu1', 'es', 'IR A PERFIL'),
('home', 'p_menu2', 'es', 'CHAT PRIVADO'),
('home', 'p_menu3', 'es', 'SUGERENCIAS A CUORE'),
('home', 'p_menu4', 'es', 'CONTACTANOS'),
('home', 'p_menu5', 'es', 'CERRAR SESION'),
('home', 'c_comentario_personal', 'es', 'Comentarios...'),
('home', 'eliminar_comentario', 'es', 'Eliminar'),
('home', 'server_error_10', 'es', 'Máximo 255 caracteres'),
('home', 'server_error_510', 'es', 'No hay recomendaciones disponibles'),
('home', 'server_error_511', 'es', 'Error al actualizar la reacción'),
('home', 'server_error_517', 'es', 'Error borrando comentario'),
('home', 'server_error_519', 'es', 'Error enviando comentario'),
('home', 'server_error_521', 'es', "No existe la publicación"),
('home', 'server_error_522', 'es', "Error al loguearse con este usuario"),
('home', 'server_error_523', 'es', "Error realizando el pago"),
('home', 'server_error_999', 'es', 'Token expirado'),
('home', 'validation_7', 'es', 'Introduzca el nombre por favor'),
('home', 'validation_8', 'es', 'Introduzca el ISBN por favor'),
('home', 'validation_9', 'es', 'Introduzca una fehca válida por favor'),
('home', 'validation_10', 'es', 'Introduzca el cvv por favor'),
('home', 'validation_11', 'es', 'Tarjeta no válida, inténtelo de nuevo'),
('home', 'validation_12', 'es', 'La fecha introducida no es correcta'),
('home', 'validation_13', 'es', 'El cvv no es correcto'),
('home', 'boton_premium', 'es', 'HAZTE PREMIUM'),
('home', 'titulo_premium', 'es', "El hacerte PREMIUM será para siempre, solamente deberás abonar el módico precio de '19,99$'"),
('home', 'titulo_nombre_completo', 'es', 'Nombre completo: '),
('home', 'titulo_isbn', 'es', 'ISBN: '),
('home', 'titulo_caducidad', 'es', 'Caducidad: '),
('home', 'titulo_cvv', 'es', 'CVV: '),
('home', 'pago_realizado_correctamente', 'es', 'El pago se ha completado correctamente, ¡Gracias!'),
('home', 'confirmar_alerta', 'es', 'Confirmar'),
('home', 'cancelar_alerta', 'es', 'Cancelar'),
('home', 'correcto', 'es', 'Éxito'),
('home', 'realizando_pago', 'es', 'Realizando pago, espere un segundo'),
('home', 'restringido_no_superadmin', 'en', 'Restricted area for non-super administrator users'),
('home', 'p_menu1', 'en', 'GO TO PROFILE'),
('home', 'p_menu2', 'en', 'PRIVATE CHAT'),
('home', 'p_menu3', 'en', 'SUGGESTIONS TO CUORE'),
('home', 'p_menu4', 'en', 'CONTACT US'),
('home', 'p_menu5', 'en', 'SIGN OFF'),
('home', 'c_comentario_personal', 'en', 'Comments...'),
('home', 'eliminar_comentario', 'en', 'Remove'),
('home', 'server_error_10', 'en', 'Maximum 255 characters'),
('home', 'server_error_510', 'en', 'Not recommendations available!'),
('home', 'server_error_511', 'en', 'Error updating the reaction!'),
('home', 'server_error_517', 'en', 'Error deleting comment'),
('home', 'server_error_519', 'en', 'Error sending comment'),
('home', 'server_error_521', 'en', "The publication does not exist"),
('home', 'server_error_522', 'en', "Error logging in with this user"),
('home', 'server_error_523', 'en', "Error making the payment"),
('home', 'server_error_999', 'en', 'Expired token'),
('home', 'validation_7', 'en', 'Please enter name'),
('home', 'validation_8', 'en', 'Please enter ISBN'),
('home', 'validation_9', 'en', 'Please enter a valid date'),
('home', 'validation_10', 'en', 'Please enter cvv'),
('home', 'validation_11', 'en', 'Invalid card, please try again'),
('home', 'validation_12', 'en', 'The entered date is not correct'),
('home', 'validation_13', 'en', 'The cvv is not correct'),
('home', 'boton_premium', 'en', 'GO PREMIUM'),
('home', 'titulo_premium', 'en', "Becoming PREMIUM will be forever, you only have to pay the small price of '$19.99'"),
('home', 'titulo_nombre_completo', 'en', 'Full name: '),
('home', 'titulo_isbn', 'en', 'ISBN: '),
('home', 'titulo_caducidad', 'en', 'Expiration: '),
('home', 'titulo_cvv', 'en', 'CVV: '),
('home', 'pago_realizado_correctamente', 'en', 'Payment completed successfully, Thank you!'),
('home', 'confirmar_alerta', 'en', 'Confirm'),
('home', 'cancelar_alerta', 'en', 'Cancel'),
('home', 'correcto', 'en', 'Success'),
('home', 'realizando_pago', 'en', 'Making payment, please wait a second'),
('home', 'restringido_no_superadmin', 'fr', 'Zone restreinte pour les utilisateurs non super-administrateurs'),
('home', 'p_menu1', 'fr', 'ALLER AU PROFIL'),
('home', 'p_menu2', 'fr', 'DISCUSSION PRIVÉE'),
('home', 'p_menu3', 'fr', 'SUGGESTIONS POUR CUORE'),
('home', 'p_menu4', 'fr', 'NOUS CONTACTER'),
('home', 'p_menu5', 'fr', 'FERMER SESSION'),
('home', 'c_comentario_personal', 'fr', 'Commentaires...'),
('home', 'eliminar_comentario', 'fr', 'Supprimer'),
('home', 'server_error_10', 'fr', '255 caractères maximum'),
('home', 'server_error_510', 'fr', 'Aucune recommandation disponible!'),
('home', 'server_error_511', 'fr', 'Erreur de mise à jour de la réaction!'),
('home', 'server_error_517', 'fr', "Erreur lors de la suppression d'un commentaire"),
('home', 'server_error_519', 'fr', "Erreur d'envoi de commentaire"),
('home', 'server_error_521', 'fr', "La publication n'existe pas"),
('home', 'server_error_522', 'fr', "Erreur de connexion avec cet utilisateur"),
('home', 'server_error_523', 'fr', "Erreur lors du paiement"),
('home', 'server_error_999', 'fr', 'Jeton expiré'),
('home', 'validation_7', 'fr', 'Veuillez entrer le nom'),
('home', 'validation_8', 'fr', "Veuillez entrer l'ISBN"),
('home', 'validation_9', 'fr', 'Veuillez entrer une date valide'),
('home', 'validation_10', 'fr', 'Veuillez entrer CV'),
('home', 'validation_11', 'fr', 'Carte invalide, veuillez réessayer'),
('home', 'validation_12', 'fr', "La date saisie n'est pas correcte"),
('home', 'validation_13', 'fr', "Le cvv n'est pas correct"),
('home', 'boton_premium', 'fr', 'PASSER EN PREMIUM'),
('home', 'titulo_premium', 'fr', "Devenir PREMIUM sera pour toujours, vous n'aurez qu'à payer le petit prix de '$19.99'"),
('home', 'titulo_isbn', 'fr', 'ISBN: '),
('home', 'titulo_nombre_completo', 'fr', 'Nom complet: '),
('home', 'titulo_caducidad', 'fr', 'Expiration: '),
('home', 'titulo_cvv', 'fr', 'CVV: '),
('home', 'pago_realizado_correctamente', 'fr', 'Le paiement a été effectué avec succès, Merci!'),
('home', 'confirmar_alerta', 'fr', 'Confirmer'),
('home', 'cancelar_alerta', 'fr', 'Annuler'),
('home', 'correcto', 'fr', 'Succès'),
('home', 'realizando_pago', 'fr', 'Paiement en cours, veuillez patienter une seconde'),
('home', 'restringido_no_superadmin', 'de', 'Eingeschränkter Bereich für Nicht-Superadministrator-Benutzer'),
('home', 'p_menu1', 'de', 'ZUM PROFIL GEHEN'),
('home', 'p_menu2', 'de', 'PRIVATER CHAT'),
('home', 'p_menu3', 'de', 'VORSCHLÄGE ZU CUORE'),
('home', 'p_menu4', 'de', 'KONTAKTIERE UNS'),
('home', 'p_menu5', 'de', 'ABMELDEN'),
('home', 'c_comentario_personal', 'de', 'Kommentare...'),
('home', 'eliminar_comentario', 'de', 'Entfernen'),
('home', 'server_error_10', 'de', 'Maximal 255 Zeichen'),
('home', 'server_error_510', 'de', 'Keine Empfehlungen verfügbar!'),
('home', 'server_error_511', 'de', 'Fehler bei der Aktualisierung der Reaktion!'),
('home', 'server_error_517', 'de', 'Fehler beim Löschen eines Kommentars'),
('home', 'server_error_519', 'de', 'Fehler beim Senden des Kommentars'),
('home', 'server_error_521', 'de', "Die Veröffentlichung existiert nicht"),
('home', 'server_error_522', 'de', "Fehler bei der Anmeldung mit diesem Benutzer"),
('home', 'server_error_523', 'de', "Fehler bei der Zahlung"),
('home', 'server_error_999', 'de', 'Abgelaufenes Token'),
('home', 'validation_7', 'de', 'Bitte namen eingeben'),
('home', 'validation_8', 'de', 'Geben sie bitte die ISBN ein'),
('home', 'validation_9', 'de', 'Bitte gib ein korrektes Datum an'),
('home', 'validation_10', 'de', 'Geben Sie bitte den Lebenslauf ein'),
('home', 'validation_11', 'de', 'Ungültige Karte, bitte versuchen Sie es erneut'),
('home', 'validation_12', 'de', 'Das eingegebene Datum ist nicht korrekt'),
('home', 'validation_13', 'de', 'Der cvv ist nicht korrekt'),
('home', 'boton_premium', 'de', 'PRÄMIE GEHEN'),
('home', 'titulo_premium', 'de', "PREMIUM zu werden wird für immer sein, Sie müssen nur den kleinen Preis von '$19.99' bezahlen."),
('home', 'titulo_nombre_completo', 'de', 'Vollständiger Name: '),
('home', 'titulo_isbn', 'de', 'ISBN: '),
('home', 'titulo_caducidad', 'de', 'Ablauf: '),
('home', 'titulo_cvv', 'de', 'CVV: '),
('home', 'pago_realizado_correctamente', 'de', 'Die Zahlung wurde erfolgreich abgeschlossen, danke!'),
('home', 'confirmar_alerta', 'de', 'Bestätigen'),
('home', 'cancelar_alerta', 'de', 'Stornieren'),
('home', 'correcto', 'de', 'Erfolg'),
('home', 'realizando_pago', 'de', 'Zahlung ausführen, bitte warten Sie eine Sekunde'),
('chatPrivado', 'restringido_no_superadmin', 'es', 'Zona restringida para usuarios no superadministradores'),
('chatPrivado', 'input_buscador', 'es', 'Buscador...'),
('chatPrivado', 'comentario', 'es', 'Envía Mensaje ...'),
('chatPrivado', 'p_menu1', 'es', 'IR A PERFIL'),
('chatPrivado', 'p_menu2', 'es', 'SUGERENCIAS A CUORE'),
('chatPrivado', 'p_menu3', 'es', 'CONTACTANOS'),
('chatPrivado', 'p_menu4', 'es', 'CERRAR SESION'),
('chatPrivado', 'server_error_10', 'es', 'Máximo 255 caracteres'),
('chatPrivado', 'server_error_520', 'es', "Error al enviar el mensaje"),
('chatPrivado', 'server_error_522', 'es', "Error al loguearse con este usuario"),
('chatPrivado', 'error_chat', 'es', "No se puede conectar al chat. Contacta con <a href = 'mailto:cuore.soporte@gmail.com'>cuore.soporte@gmail.com</a>"),
('chatPrivado', 'restringido_premium', 'es', "Es una zona restringida para usuarios premium"),
('chatPrivado', 'error_usuario_envia_socket', 'es', "Error emisor mensaje"),
('chatPrivado', 'error_mensaje_socket', 'es', "El mensaje no puede estar vacío"),
('chatPrivado', 'error_usuario_recibe_socket', 'es', "Error receptor mensaje"),
('chatPrivado', 'restringido_no_superadmin', 'en', 'Restricted area for non-super administrator users'),
('chatPrivado', 'input_buscador', 'en', 'Search...'),
('chatPrivado', 'comentario', 'en', 'Send Message...'),
('chatPrivado', 'p_menu1', 'en', 'GO TO PROFILE'),
('chatPrivado', 'p_menu2', 'en', 'SUGGESTIONS TO CUORE'),
('chatPrivado', 'p_menu3', 'en', 'CONTACT US'),
('chatPrivado', 'p_menu4', 'en', 'SIGN OFF'),
('chatPrivado', 'server_error_10', 'en', 'Máximo 255 caracteres'),
('chatPrivado', 'server_error_520', 'en', "Error sending the message"),
('chatPrivado', 'server_error_522', 'en', "Error logging in with this user"),
('chatPrivado', 'error_chat', 'en', "Cannot connect to chat. contact with <a href = 'mailto:cuore.soporte@gmail.com'>cuore.soporte@gmail.com</a>"),
('chatPrivado', 'restringido_premium', 'en', "It is a restricted area for premium users"),
('chatPrivado', 'error_usuario_envia_socket', 'en', "Message sender error"),
('chatPrivado', 'error_mensaje_socket', 'en', "The message cannot be empty"),
('chatPrivado', 'error_usuario_recibe_socket', 'en', "Message receiver error"),
('chatPrivado', 'restringido_no_superadmin', 'fr', 'Zone restreinte pour les utilisateurs non super-administrateurs'),
('chatPrivado', 'input_buscador', 'fr', 'Chercheur...'),
('chatPrivado', 'comentario', 'fr', 'Envoyer Message...'),
('chatPrivado', 'p_menu1', 'fr', 'ALLER AU PROFIL'),
('chatPrivado', 'p_menu2', 'fr', 'SUGGESTIONS POUR CUORE'),
('chatPrivado', 'p_menu3', 'fr', 'NOUS CONTACTER'),
('chatPrivado', 'p_menu4', 'fr', 'FERMER SESSION'),
('chatPrivado', 'server_error_10', 'fr', 'Máximo 255 caracteres'),
('chatPrivado', 'server_error_520', 'fr', "Erreur lors de l'envoi du message"),
('chatPrivado', 'server_error_522', 'fr', "Erreur de connexion avec cet utilisateur"),
('chatPrivado', 'error_chat', 'fr', "Impossible de se connecter au chat. Contacter avec <a href = 'mailto:cuore.soporte@gmail.com'>cuore.soporte@gmail.com</a>"),
('chatPrivado', 'restringido_premium', 'fr', "C'est une zone restreinte pour les utilisateurs premium"),
('chatPrivado', 'error_usuario_envia_socket', 'fr', "Erreur de l'expéditeur du message"),
('chatPrivado', 'error_mensaje_socket', 'fr', "Le message ne peut pas être vide"),
('chatPrivado', 'error_usuario_recibe_socket', 'fr', "Erreur du destinataire du message"),
('chatPrivado', 'restringido_no_superadmin', 'de', 'Eingeschränkter Bereich für Nicht-Superadministrator-Benutzer'),
('chatPrivado', 'input_buscador', 'de', 'Suchmaschine...'),
('chatPrivado', 'comentario', 'de', 'Nachricht Senden...'),
('chatPrivado', 'p_menu1', 'de', 'ZUM PROFIL GEHEN'),
('chatPrivado', 'p_menu2', 'de', 'VORSCHLÄGE ZU CUORE'),
('chatPrivado', 'p_menu3', 'de', 'KONTAKTIERE UNS'),
('chatPrivado', 'p_menu4', 'de', 'ABMELDEN'),
('chatPrivado', 'server_error_10', 'de', 'Máximo 255 caracteres'),
('chatPrivado', 'server_error_520', 'de', "Fehler beim Senden der Nachricht"),
('chatPrivado', 'server_error_522', 'de', "Fehler bei der Anmeldung mit diesem Benutzer"),
('chatPrivado', 'error_chat', 'de', "Keine Verbindung zum Chat möglich. Kontakt mit <a href = 'mailto:cuore.soporte@gmail.com'>cuore.soporte@gmail.com</a>"),
('chatPrivado', 'restringido_premium', 'de', "Es ist ein eingeschränkter Bereich für Premium-Benutzer"),
('chatPrivado', 'error_usuario_envia_socket', 'de', "Fehler beim Absender der Nachricht"),
('chatPrivado', 'error_mensaje_socket', 'de', "Die Nachricht darf nicht leer sein"),
('chatPrivado', 'error_usuario_recibe_socket', 'de', "Nachrichtenempfängerfehler"),
('superadmin', 'restringido_superadmin', 'es', 'Zona restringida para usuarios superadministradores'),
('superadmin', 'input_buscador', 'es', 'Buscador...'),
('superadmin', 'label_email', 'es', 'Correo:'),
('superadmin', 'email_title', 'es', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('superadmin', 'label_premium', 'es', 'Premium:'),
('superadmin', 'label_clave', 'es', 'Restablecer contraseña:'),
('superadmin', 'clave_registro_title', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('superadmin', 'boton_actualizar', 'es', 'ACTUALIZAR'),
('superadmin', 'boton_borrar', 'es', 'ELIMINAR'),
('superadmin', 'titulo_borrar', 'es', '¿Está seguro?'),
('superadmin', 'texto_borrar', 'es', 'No podrá deshacer esta acción.'),
('superadmin', 'confirmar_alerta', 'es', 'Confirmar'),
('superadmin', 'usuario_borrado_correctamente', 'es', 'El usuario ha sido eliminado'),
('superadmin', 'usuario_actualizado_correctamente', 'es', 'Usuario actualizado'),
('superadmin', 'error_envio_correo', 'es', "No ha sido posible enviar el correo"),
('superadmin', 'correcto', 'es', 'Éxito'),
('superadmin', 'server_error_3', 'es', 'El email debe tener un formato similar a: xxxx@xxxx.xxx'),
('superadmin', 'server_error_4', 'es', 'La contraseña debe contener al menos 8 carácteres: una minúscula, una mayúscula, un número y no puede contener espacios.'),
('superadmin', 'server_error_512', 'es', 'Error actualizando perfil'),
('superadmin', 'server_error_513', 'es', 'El email pertenece a otro usuario'),
('superadmin', 'server_error_522', 'es', "Error al loguearse con este usuario"),
('superadmin', 'server_error_524', 'es', "El usuario no existe"),
('superadmin', 'server_error_525', 'es', "Error al borrar el usuario"),
('superadmin', 'server_error_999', 'es', "Token expirado"),
('superadmin', 'restringido_superadmin', 'en', 'Restricted area for super administrator users'),
('superadmin', 'input_buscador', 'en', 'Seeker...'),
('superadmin', 'label_email', 'en', 'Mail:'),
('superadmin', 'email_title', 'en', 'The email must have a format similar to: xxxx@xxxx.xxx'),
('superadmin', 'label_premium', 'en', 'Premium:'),
('superadmin', 'label_clave', 'en', 'Restore password:'),
('superadmin', 'clave_registro_title', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('superadmin', 'boton_actualizar', 'en', 'UPDATE'),
('superadmin', 'boton_borrar', 'en', 'REMOVE'),
('superadmin', 'titulo_borrar', 'en', 'Are you sure?'),
('superadmin', 'texto_borrar', 'en', 'You will not be able to undo this action.'),
('superadmin', 'confirmar_alerta', 'en', 'Confirm'),
('superadmin', 'usuario_borrado_correctamente', 'en', 'The user has been removed'),
('superadmin', 'usuario_actualizado_correctamente', 'en', 'Updated user'),
('superadmin', 'error_envio_correo', 'en', "It has not been possible to send the email"),
('superadmin', 'correcto', 'en', 'Success'),
('superadmin', 'server_error_3', 'en', 'The email must have a format similar to: xxxx@xxxx.xxx'),
('superadmin', 'server_error_4', 'en', 'The password must contain at least 8 characters: one lower case, one upper case, one number and cannot contain spaces.'),
('superadmin', 'server_error_512', 'en', 'Error updating profile'),
('superadmin', 'server_error_513', 'en', 'The email belongs to another user'),
('superadmin', 'server_error_522', 'en', "Error logging in with this user"),
('superadmin', 'server_error_524', 'en', "Username does not exist"),
('superadmin', 'server_error_525', 'en', "Error deleting user"),
('superadmin', 'server_error_999', 'en', "Expired token"),
('superadmin', 'restringido_superadmin', 'fr', 'Zone restreinte pour les utilisateurs super-administrateurs'),
('superadmin', 'input_buscador', 'fr', 'Chercheur...'),
('superadmin', 'label_email', 'fr', 'Poster:'),
('superadmin', 'email_title', 'fr', "L'e-mail doit avoir un format similaire à : xxxx@xxxx.xxx"),
('superadmin', 'label_premium', 'fr', 'Prime:'),
('superadmin', 'label_clave', 'fr', 'Restaurer le mot de passe:'),
('superadmin', 'clave_registro_title', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne peut pas contenir d'espaces."),
('superadmin', 'boton_actualizar', 'fr', 'METTRE À JOUR'),
('superadmin', 'boton_borrar', 'fr', 'ÉLIMINER'),
('superadmin', 'titulo_borrar', 'fr', 'Êtes-vous sûr?'),
('superadmin', 'texto_borrar', 'fr', 'Vous ne pourrez pas annuler cette action.'),
('superadmin', 'confirmar_alerta', 'fr', 'Confirmer'),
('superadmin', 'usuario_borrado_correctamente', 'fr', "L'utilisateur a été supprimé"),
('superadmin', 'usuario_actualizado_correctamente', 'fr', 'utilisateur mis à jour'),
('superadmin', 'error_envio_correo', 'fr', "Il n'a pas été possible d'envoyer l'e-mail"),
('superadmin', 'correcto', 'fr', 'Succès'),
('superadmin', 'server_error_3', 'fr', "L'email doit avoir un format similaire à : xxxx@xxxx.xxx"),
('superadmin', 'server_error_4', 'fr', "Le mot de passe doit contenir au moins 8 caractères : une minuscule, une majuscule, un chiffre et ne doit pas contenir d'espaces."),
('superadmin', 'server_error_512', 'fr', 'Erreur lors de la mise à jour du profil'),
('superadmin', 'server_error_513', 'fr', "L'e-mail appartient à un autre utilisateur"),
('superadmin', 'server_error_522', 'fr', "Erreur de connexion avec cet utilisateur"),
('superadmin', 'server_error_524', 'fr', "Le nom d'utilisateur n'existe pas"),
('superadmin', 'server_error_525', 'fr', "Erreur lors de la suppression de l'utilisateur"),
('superadmin', 'server_error_999', 'fr', "jeton expiré"),
('superadmin', 'restringido_superadmin', 'de', 'Eingeschränkter Bereich für Superadministratoren'),
('superadmin', 'input_buscador', 'de', 'Sucher...'),
('superadmin', 'label_email', 'de', 'Post:'),
('superadmin', 'email_title', 'de', 'Die E-Mail muss ein ähnliches Format haben wie: xxxx@xxxx.xxx'),
('superadmin', 'label_premium', 'de', 'Prämie:'),
('superadmin', 'label_clave', 'de', 'Passwort wiederherstellen:'),
('superadmin', 'clave_registro_title', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('superadmin', 'boton_actualizar', 'de', 'AKTUALISIEREN'),
('superadmin', 'boton_borrar', 'de', 'LÖSCHEN'),
('superadmin', 'titulo_borrar', 'de', 'Bist du sicher?'),
('superadmin', 'texto_borrar', 'de', 'Sie können diese Aktion nicht rückgängig machen.'),
('superadmin', 'confirmar_alerta', 'de', 'Bestätigen'),
('superadmin', 'usuario_borrado_correctamente', 'de', 'Der Benutzer wurde entfernt'),
('superadmin', 'usuario_actualizado_correctamente', 'de', 'Aktualisierter benutzer'),
('superadmin', 'error_envio_correo', 'de', "Es war nicht möglich, die Mail zu versenden"),
('superadmin', 'correcto', 'de', 'Erfolg'),
('superadmin', 'server_error_3', 'de', 'Die E-Mail sollte ein ähnliches format haben wie: xxxx@xxxx.xxx'),
('superadmin', 'server_error_4', 'de', 'Das Passwort muss mindestens 8 Zeichen enthalten: einen Kleinbuchstaben, einen Großbuchstaben, eine Zahl und darf keine Leerzeichen enthalten.'),
('superadmin', 'server_error_512', 'de', 'Fehler beim Aktualisieren des Profils'),
('superadmin', 'server_error_513', 'de', 'Die E-Mail gehört einem anderen Benutzer'),
('superadmin', 'server_error_522', 'de', "Fehler bei der Anmeldung mit diesem Benutzer"),
('superadmin', 'server_error_524', 'de', "der Benutzername existiert nicht"),
('superadmin', 'server_error_525', 'de', "Fehler beim Löschen des Benutzers"),
('superadmin', 'server_error_999', 'de', "Abgelaufenes Token"),
('match', 'restringido_no_superadmin', 'es', 'Zona restringida para usuarios no superadministradores'),
('match', 'titulo_bloque1', 'es', 'Usuarios a los que les has pedido cita'),
('match', 'titulo_bloque2', 'es', 'Usuarios que han aceptado la cita'),
('match', 'boton_borrar', 'es', 'Eliminar'),
('match', 'p_menu1', 'es', 'IR A PERFIL'),
('match', 'p_menu2', 'es', 'SUGERENCIAS A CUORE'),
('match', 'p_menu3', 'es', 'CONTACTANOS'),
('match', 'p_menu4', 'es', 'CERRAR SESION'),
('match', 'restringido_no_superadmin', 'en', 'Restricted area for non-super administrator users'),
('match', 'titulo_bloque1', 'en', 'Users you have asked for an appointment'),
('match', 'titulo_bloque2', 'en', 'Users who have accepted the appointment'),
('match', 'boton_borrar', 'en', 'Remove'),
('match', 'p_menu1', 'en', 'GO TO PROFILE'),
('match', 'p_menu2', 'en', 'SUGGESTIONS TO CUORE'),
('match', 'p_menu3', 'en', 'CONTACT US'),
('match', 'p_menu4', 'en', 'SIGN OFF'),
('match', 'restringido_no_superadmin', 'fr', 'Zone restreinte pour les utilisateurs non super-administrateurs'),
('match', 'titulo_bloque1', 'fr', 'Utilisateurs pour lesquels vous avez demandé un rendez-vous'),
('match', 'titulo_bloque2', 'fr', 'Utilisateurs ayant accepté le rendez-vous'),
('match', 'boton_borrar', 'fr', 'Supprimer'),
('match', 'p_menu1', 'fr', 'ALLER AU PROFIL'),
('match', 'p_menu2', 'fr', 'SUGGESTIONS POUR CUORE'),
('match', 'p_menu3', 'fr', 'NOUS CONTACTER'),
('match', 'p_menu4', 'fr', 'FERMER SESSION'),
('match', 'restringido_no_superadmin', 'de', 'Eingeschränkter Bereich für Nicht-Superadministrator-Benutzer'),
('match', 'titulo_bloque1', 'de', 'Benutzer, die Sie um einen Termin gebeten haben'),
('match', 'titulo_bloque2', 'de', 'Benutzer, die den Termin angenommen haben'),
('match', 'boton_borrar', 'de', 'Entfernen'),
('match', 'p_menu1', 'de', 'ZUM PROFIL GEHEN'),
('match', 'p_menu2', 'de', 'VORSCHLÄGE ZU CUORE'),
('match', 'p_menu3', 'de', 'KONTAKTIERE UNS'),
('match', 'p_menu4', 'de', 'ABMELDEN');
