CREATE DATABASE IF NOT EXISTS Cuore;
USE Cuore;

CREATE TABLE IF NOT EXISTS usuarios (
    nick VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    pass VARCHAR(10) NOT NULL,
    rol ENUM (chicaBUSCAchica, chicaBUSCAchico, chicoBUSCAchico, chicoBUSCAchica, chic@BUSCAchic@),
    imagen VARCHAR(300) NOT NULL,
    video_present VARCHAR(500) NOT NULL,
    PRIMARY KEY (nick)
);

CREATE TABLE IF NOT EXISTS publicaciones(
    idPublicacion INT UNSIGNED AUTO_INCREMENT,
    nick VARCHAR(50) NOT NULL,
    texto VARCHAR (500),
    imagen VARCHAR(300),
    creado DATETIME NOT NULL,
    PRIMARY KEY (idPublicacion),
    FOREIGN KEY (nick) REFERENCES usuarios (nick) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS mensajes (
    idMensaje INT UNSIGNED AUTO_INCREMENT,
    nick VARCHAR(50) NOT NULL, 
    email VARCHAR(50) NOT NULL,       //ME REFIERO AL EMAIL DEL DESTINATARIO, PARA QUE A ESTE LE LLEGUE UN MENSAJE PERSONAL              
    texto VARCHAR (500) NOT NULL,
    creado DATETIME NOT NULL,
    PRIMARY KEY (idMensaje),
    FOREIGN KEY (nick) REFERENCES usuarios (nick) ON DELETE CASCADE ON UPDATE CASCADE
);